### ISSUE TITLE
Usage of "Buffer" requires polyfill for use on web

### ISSUE THREAD

**Issue by Venryx** [taskcluster/slugid#12]
I've been using `slugid` for a couple years now, and am happy with it. However, today I tried using it in a new web project, and I had this error on calling `v4()`:
```
slugid.v2.0.0.js:58 Uncaught ReferenceError: Buffer is not defined
    at Object.v4 (slugid.v2.0.0.js:58)
    at GenerateUUID (KeyGenerator.js:13)
    at new TodoEntry (@TodoEntry.js:4)
    at onClick (TodoList.js:40)
    at HTMLUnknownElement.callCallback (react-dom.v17.0.2.js:3952)
    at Object.invokeGuardedCallbackDev (react-dom.v17.0.2.js:4001)
    at invokeGuardedCallback (react-dom.v17.0.2.js:4063)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.v17.0.2.js:4077)
    at executeDispatch (react-dom.v17.0.2.js:8250)
    at processDispatchQueueItemsInOrder (react-dom.v17.0.2.js:8282)
```

Using the dev-tools, I confirmed that `window.Buffer` is undefined.

I then opened up my previous websites, to see how the `new Buffer(16)` line was managing to run in my previous web projects. Apparently it is getting its `Buffer` implementation from the [buffer](https://github.com/feross/buffer) module.

I don't understand how that package's `Buffer` implementation is being made available to the [slugid.js](https://github.com/taskcluster/slugid/blob/main/slugid.js) file though; it is neither imported/required, nor is it available on the global `window` object.

So anyway, I have two questions:
1) How is slugid managing to reference the `Buffer` implementation from the [buffer](https://github.com/feross/buffer) package if it never imports it, and it's not available on `window`?
2) What is the recommended way to make `Buffer` available to `slugid` in the web browser?

Thanks.

**Comment by djmitche** [comment]
Typically the "build" process for code that runs on the browser automatically detects use of objects like this and polyfills them.  My understanding is that this is the "right" way to do so.  The module is not built to be directly included in a web-browser context.

**Comment by Venryx** [comment]
Yes, somehow my old build process was including the `Buffer` implementation, even though I couldn't see the reference available in the code. (I suppose it was added somewhere that Javascript's sourcemaps left out)

Anyway, if it is working as intended, I will close it now. (anyway, there are workarounds for the manual case; just import from the [buffer](https://github.com/feross/buffer) package, then attach it as `window.Buffer`)

**Comment by djmitche** [comment]
Thanks!  I seem to recall something changed in either Webpack or Babel that caused issues with this.  I have _minimal_ understanding of both of those tools, so the issues I saw might have been operator error!

**Comment by Venryx** [comment]
Now that webpack 5 [no longer includes NodeJS polyfills by default](https://webpack.js.org/migrate/5/#run-a-single-build-and-follow-advises), it may be worth mentioning in the readme that the library requires NodeJS polyfills to be used in the browser.

For others hitting this issue, there are two ways to solve:
1) Including the NodeJS polyfills explicitly, by modifying your webpack config. (either module-by-module, as [seen here](https://github.com/diegomura/react-pdf/issues/1029), or using a "mega polyfill", as [seen here](https://github.com/Richienb/node-polyfill-webpack-plugin))
2) Making a fork of the given library, adding and importing from the needed polyfills/isomorphic-modules as explicit dependencies. (this is what I'm currently doing, as I like libraries to be "fully encapsulated" and usable from both nodejs and web without needing webpack-config modifications; there are ways you can also make separate builds, with the nodejs build using the built-in modules, and the web build using the polyfill, but in most cases I just produce a single build that uses the polyfill/isomorphic-module because I'm too lazy to set up the multi-build configuration)

**Comment by jwhitlock** [comment]
I'm going to re-open so that this latest comment is shown on an open issue. I also have minimal understanding of these issues, so I'm curious if others have suggestions. I think we can close this with a README change.

**Comment by jwhitlock** [comment]
I noticed that https://github.com/uuidjs/uuid supports browsers without a polyfill. The API we use:

* [uuid.parse](https://github.com/uuidjs/uuid/blob/1c849da6e164259e72e18636726345b13a7eddd6/src/parse.js#L3-L39) returns a ``Uint8Array(16)``
* [uuid.stringify](https://github.com/uuidjs/uuid/blob/1c849da6e164259e72e18636726345b13a7eddd6/src/stringify.js#L13-L49) uses offsets into the passed "array", so it could work with a node `Buffer` or a JS `ArrayBuffer`
* [uuid.v4](https://github.com/uuidjs/uuid/blob/1c849da6e164259e72e18636726345b13a7eddd6/src/v4.js#L4-L25) uses offsets as well to copy the data into the passed "buf"

The returns from functions are strings, so we could potentially avoid `Buffer` in the implementation, and remove the need for a polyfill for web targets.
