### ISSUE TITLE
Please publish a new release to npmjs

### ISSUE THREAD

**Issue by benediktarnold** [taskcluster/slugid#15]
Hi!
My project depends on slugid@2.0.0 which has a dependency to uuid@^3.2.1. I changed some of my other dependencies and uuid resolved to version 8.3.2 This failed my webpack build since the way how slugid imports uuid is deprecated https://www.npmjs.com/package/uuid#upgrading-from-uuid3x

Since you already solved that in https://github.com/taskcluster/slugid/commit/ebc115f21a63bb29aaa9c35748591929432d2590 could you please publish a new version to npmjs?

Thanks in advance,
Ben

**Comment by jwhitlock** [comment]
Yes, but I want to get CI working first (issue #14) so we can confirm the changes in PR #13 and future PRs. I think it will be Aug 2 at the earliest for the next release.

**Comment by jwhitlock** [comment]
Version 3.0.0 is published: https://www.npmjs.com/package/slugid/v/3.0.0
