### ISSUE TITLE
module not found error

### ISSUE THREAD

**Issue by micalevisk** [taskcluster/slugid#31]
there's no `main` entry on `package.json` and on `index.js` in the root, which means that we cannot use `require('slugid')`

### steps to reproduce

```
npm i slugid
node -r slugid
```

![image](https://github.com/taskcluster/slugid/assets/13461315/3a9f2ca9-7b8e-4fe7-8d04-7e564f6768ab)

### my suggestions

- add the [`main`](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#main) entry to your `package.json` pointing to `src/index.js`
- to reduce the amount of file being publish to NPM, add the entry [`files`](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#files) and list only source files

**Comment by djmitche** [comment]
Huh, this worked once upon a time! But that time may have been the node 0.xx era.

Would you like to make a PR?
