### ISSUE TITLE
Image not showing

### ISSUE THREAD

**Issue by Venryx** [taskcluster/slugid#5]
By the way, there is an image above the "build: passing" text on the readme page, which is showing up as a blank square. (obviously not a big issue, just thought I'd mention)

Thanks for the package by the way. 22 characters is still pretty long, but it's much more acceptable in a url than the full 36/32 character version.

**Comment by djmitche** [comment]
Thanks!  Logos are now at https://github.com/taskcluster/taskcluster-media but I guess we've never gotten around to fixing links..

**Comment by djmitche** [comment]
@Venryx I'm curious if you're using slugid outside of Taskcluster?

**Comment by Venryx** [comment]
Indeed I am! I'm using it in this project: https://github.com/canonical-debate-lab/client

I chose this package over a couple others on npm (eg. https://github.com/futoin/util-js-uuid), because this one has more stars, a better readme, a better api (imo), and chooses "-" and "_" as the two non-alphanumeric characters (which seem the best to me).

**Comment by djmitche** [comment]
very cool -- thanks for the note!
