### ISSUE TITLE
Conflicting license statements: MIT vs. MPL 2.0

### ISSUE THREAD

**Issue by mnoorenberghe** [taskcluster/slugid#8]
The [README.md](https://github.com/taskcluster/slugid/blob/6750a8e468eab5df9cc9fa4b5e460e7d60d4005c/README.md), [package.json](https://github.com/taskcluster/slugid/blob/6750a8e468eab5df9cc9fa4b5e460e7d60d4005c/package.json#L6), header of [slugid.js](https://github.com/taskcluster/slugid/blob/6750a8e468eab5df9cc9fa4b5e460e7d60d4005c/slugid.js), and header of [slugid_test.js](https://github.com/taskcluster/slugid/blob/6750a8e468eab5df9cc9fa4b5e460e7d60d4005c/slugid_test.js) all claim the code is MIT licensed, whereas [LICENSE](https://github.com/taskcluster/slugid/blob/6750a8e468eab5df9cc9fa4b5e460e7d60d4005c/LICENSE) specifies MPL 2.0.

It seems like the `LICENSE` file is incorrect and should be replaced.

**Comment by djmitche** [comment]
Indeed, it looks like this was one of the first pieces of code in Taskcluster and perhaps written before the author was aware of the MPL.  Rather than re-license, I'll just fix the LICENSE file.

Thanks for the heads-up!
